---
- name: Creating new file
  hosts: managednodes
  become: yes
  tasks:
    - name: Creating a new file
      file: 
         path: /home/ubuntu/file.txt
         state: touch
         mode: 0755
      register: result
    - name: Debugging
      debug:
        var: result
