---
- name: installing git unzip and wget
  hosts: medium
  become: yes
  become_method: sudo
  tasks:
    - name: installing git unzip and wget
      yum:
         name: "{{ item }}"
         state: present
      with_items:
         - git
         - unzip
         - wget
      
