---
- name: Configuring NTP service
  hosts: all
  become: yes
  tasks:
    - name: Installing NTP Service
      apt:
        name: ntp
        state: present
    - name:
      service: 
          name: httpd
          enabled: yes
