---
- name: Automated reboots using Ansible
  hosts: managed
  become: yes
  tasks:
  - name:  Automated reboot
    cron:
      name: "a job for reboot"
      minute: "0"
      hour: "23"
      day: "*"
      month: "*"
      weekday: "0"
      job: "/sbin/reboot"
    register: result
  - name: debugging
    debug:
       var: result
