---
- name: Sonarqube setup and start
  hosts: medium
  become_method: sudo
  become: yes
  tasks:
     - name: installing wget and unzip
       file:
          path: /opt/sonarqube-7.6
          state: absent

     - name: Extracting downloaded sonarqube zip
       unarchive:
           src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.6.zip
           dest: /opt
           remote_src: yes
           owner: jenkins

     - name: Starting Sonarqube
       command: /opt/sonarqube-7.6/bin/linux-x86-64/sonar.sh start
       become_user: jenkins
      
     - name: Waiting for tomcat to come up on port 9000
       wait_for: host=0.0.0.0 port=9000

