---
- name: Installing app in tomcat
  hosts: medium
  become: yes
  tasks:
     - name: Deleting old tomcat installation
       file:
         path: /opt/tomcat
         state: absent
     
     - name: Creating tomcat installation directory
       file:
         path: /opt/tomcat
         state: directory
         mode: 0777
      
     - name: downloading java
       shell: 'curl -v -j -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm > /opt/jdk-8u112-linux-x64.rpm'

#    - name: installing java
#       command: rpm -ivh /opt/jdk-8u112-linux-x64.rpm
     - name: installing java
       yum:
          name: /opt/jdk-8u112-linux-x64.rpm
          state: present
  
     - name: Extracting downloaded tomcat archive
       unarchive:
         src: https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.46/bin/apache-tomcat-8.5.46.tar.gz
         dest: /opt/tomcat
         remote_src: yes
         owner: jenkins
         group: jenkins
         extra_opts: [--strip-components=1]
  
     - name: Copying tomcat users.xml
       copy:
         src: tomcat-users.xml
         dest: /opt/tomcat/conf

     - name: Copying tomcat server.xml
       copy:
        src: server.xml
        dest: /opt/tomcat/conf

     - name: Copying tomcat context.xml
       copy:
        src: context.xml
        dest: /opt/tomcat/webapps/manager/META-INF
 
     - name: Starting Tomcat
       command: nohup /opt/tomcat/bin/startup.sh &

     - name: Waiting for tomcat to come up on port 9080
       wait_for: host=0.0.0.0 port=9080

